"""Add file_path and remove file_content from resumes

Revision ID: 4c797f299193
Revises: bf069c448f3b
Create Date: 2026-06-10 12:14:53.495713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c797f299193'
down_revision: Union[str, Sequence[str], None] = 'bf069c448f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('resumes', 'file_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
