"""remove_embedding_add_skills_keywords

Revision ID: 7a7971a9162f
Revises: db8da1ab52ea
Create Date: 2026-05-20 13:00:27.611260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a7971a9162f'
down_revision: Union[str, Sequence[str], None] = 'db8da1ab52ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('skills_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('resumes', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'skills_keywords')
    # ### end Alembic commands ###
