"""Add file storage to resume model

Revision ID: bf069c448f3b
Revises: 0123a249db06
Create Date: 2026-06-10 11:52:01.034382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf069c448f3b'
down_revision: Union[str, Sequence[str], None] = '0123a249db06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_content')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
